---
kind: job
apiVersion: batch/v1
metadata:
  name: my-experiment
spec:
  template:
    spec:
      containers:
      - name: my-experiment
        image: "tensorflow/tensorflow:1.13.1-gpu-py3"
        workingDir: /storage
        command: ["sh", "my-experiment.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: onFailure
  backoffLimit: 0
...