---
kind: job
apiVersion: batch/v1
metadata:
  name: my-job # the name for the job
spec:
  template:
    spec:
      containers:
      - name: my-container # a name for the container
        image: "tensorflow/tensorflow:1.13.1-gpu-py3" # the Docker image to use
        workingDir: /storage
        command: ["sh", "python3 my_experiment.py"] # specify what should be executed when the job starts, i.e. which command to run in shell
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: onFailure
  backoffLimit: 0
...