---
kind: job
apiVersion: batch/v1
metadata:
  name: icenet_test_run # the name for the job
spec:
  template:
    spec:
      containers:
      - name: icenet_test # a name for the container
        image: "python:buster" # the Docker image to use
        workingDir: /storage/test
        command: ["echo 'hello world!'"] # specify what should be executed when the job starts, i.e. which command to run in shell
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: onFailure
  backoffLimit: 0
...